### PR TITLE
Remove non functional values from code

### PR DESCRIPTION
**Pull request by dlc-ariel**

### CODE REVIEW

**Comment by hickey** [comment]
With the removal of some of this code, the linting job has gotten better. Now it looks like there are just a number of functions that are no longer defined or maybe they have changed names?

**Comment by hickey** [comment]
Two more quick notes: 

1. There are 3 `assert`s in `test users/test_base.py` that are triggering lint errors. In fact, the file itself does not have any valid tests and probably should be removed. 
2. This work shows how vital it is that we get the pipeline in working order. There is a lint error in the `MainConfig.py` that I re-authored because I did not import the `re` module. If we had our pipeline cleaned up then this oversight would have been immediately obvious and never make it to the `master` branch.

**Comment by dlc-ariel** [comment]
@hickey Getting the following error when correctly importing the 're' library.
`Traceback (most recent call last):
  File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/ariel/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/ariel/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/ariel/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/ariel/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariel/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/ariel/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/ariel/Workspace/FTAKSERVER/FreeTakServer/FreeTAKServer/controllers/services/FTS.py", line 8, in <module>
    from FreeTAKServer.controllers.CreateStartupFilesController import CreateStartupFilesController
  File "/home/ariel/Workspace/FTAKSERVER/FreeTakServer/FreeTAKServer/controllers/CreateStartupFilesController.py", line 2, in <module>
    from FreeTAKServer.controllers.configuration.DataPackageServerConstants import DataPackageServerConstants
  File "/home/ariel/Workspace/FTAKSERVER/FreeTakServer/FreeTAKServer/controllers/configuration/DataPackageServerConstants.py", line 3, in <module>
    from FreeTAKServer.controllers.configuration.MainConfig import MainConfig
  File "/home/ariel/Workspace/FTAKSERVER/FreeTakServer/FreeTAKServer/controllers/configuration/MainConfig.py", line 9, in <module>
    class MainConfig:
  File "/home/ariel/Workspace/FTAKSERVER/FreeTakServer/FreeTAKServer/controllers/configuration/MainConfig.py", line 184, in MainConfig
    AllowedCLIIPs = re.split(r'[,:]', os.environ.get("FTS_CLI_WHITELIST")) or AllowedCLIIPs
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 206, in split
    return _compile(pattern, flags).split(string, maxsplit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
`

**Comment by hickey** [comment]
Just took a quick look and found that the `AllowedCLIIPs` is one of the variables that needs to be cleaned up to prepare #386 for merging. So good opportunity to write another test since it is a bit of a special case of how it gets handled.

**Comment by hickey** [comment]
Almost there! Only 2 more errors. 🎉

**Comment by dlc-ariel** [comment]
Im tempted to just remove the test issue. I am unsure though about the last flask user id callback issue. @naman108 can you advise what to do with the last 2 issues?

**Comment by naman108** [comment]
in terms of the current build errors the issue seems to be in the use of the flask_login module. While there is code there to implement it, I believe it is unnecessary, @dlc-ariel could you try removing the flask_login module and validating that the RestAPI is still accessible?

**Comment by hickey** [comment]
Down to one!! 

I did a tiny amount of looking into this one and certainly `listen_for_cot()` is not defined anywhere. In fact, I don't see anything that gets imported where the method would be defined. I would suggest that the test be commented out for now if we want to keep it. I would normally say comment the line and skip the test, but `result` gets defined on that line also and would have a cascading effect on the rest of the test. 

Once this test is commented out we could merge it back into master to get the testing and pipelines functional again, then assess how to handle the tests that have been identified as useful.

**Comment by dlc-ariel** [comment]
This should be good to merge if we want to move the pytest issues into a separate branch or pr

**Comment by dlc-ariel** [comment]
Also, the Sider issues remaining are all Pylint issues which I dont have the proper permissions to close. It seems we have checks for both flake8 and pylint in the pipeline, I recommend we stick to one.

**Comment by naman108** [comment]
can we confirm this has been tested and is functional?

**Pull request merged**
