### PR TITLE
minimal dependency changes to make the repository installable

### PR DESCRIPTION
**Pull request by erentar**
Certain packages are no longer installable on modern versions of linux distributions.
These changes brings them up to date.

The following dockerfile will prove that it builds and works fine

```
from fedora
run dnf update -y
run dnf groupinstall -y "Development Tools" "C Development Tools and Libraries"
run dnf install -y \
    python3 \
    python3-pip \
    cairo \
    cairo-devel \
    python3-cairo \
    python3-cairo-devel \
    python3-gevent \
    python3-lxml \
    python3-virtualenv \
    libjpeg-devel #add libjpeg to documentation

run git clone https://github.com/erentar/FreeTakServer && \
	cd FreeTakServer && \
	pip3 install .
```

### CODE REVIEW

**Comment by erentar** [comment]
Although the following error is thrown when running the server via `python3 -m FreeTAKServer.controllers.services.FTS` yields an ssl error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/appuser/.local/lib/python3.12/site-packages/FreeTAKServer/controllers/services/FTS.py", line 48, in <module>
    from FreeTAKServer.core.services.SSLDataPackageService import (
  File "/home/appuser/.local/lib/python3.12/site-packages/FreeTAKServer/core/services/SSLDataPackageService.py", line 4, in <module>
    from eventlet import listen, wrap_ssl, wsgi
  File "/home/appuser/.local/lib/python3.12/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/home/appuser/.local/lib/python3.12/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/home/appuser/.local/lib/python3.12/site-packages/eventlet/green/socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "/home/appuser/.local/lib/python3.12/site-packages/eventlet/support/greendns.py", line 45, in <module>
    from eventlet.green import ssl
  File "/home/appuser/.local/lib/python3.12/site-packages/eventlet/green/ssl.py", line 25, in <module>
    _original_wrap_socket = __ssl.wrap_socket
                            ^^^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'
```

**Comment by erentar** [comment]
Also i am still not sure if this will make the thing work properly, the dockerfile should be investigated with these changes.

**Comment by naman108** [comment]
Hey there thanks for this change, we'll give this a test and hopefully merge for 2.3

**Comment by RadioAndrea** [comment]
https://github.com/FreeTAKTeam/FreeTakServer/actions/runs/9523606683/job/26255262321

:clap: :clap: :clap:

**Pull request merged**
