### PR TITLE
Refresh of Dockerfile

### PR DESCRIPTION
**Pull request by hickey**
These changes are work to build Docker images of current FTS code base. The first step is to bring in the updates that I have been working on independently. The changes will still need some work and currently rely on the released Python packages. The eventual outcome is to install FTS code directly from the branch where the image is being built. 

Reference: #389 

Signed-off-by: Gerard Hickey <hickey@kinetic-compute.com>

### CODE REVIEW

**Comment by hickey** [comment]
Oh how I am starting to hate the GitHub Actions experience. The new Docker build workflow that I created was working pretty well and I was iterating on it to fix a few minor things. Now for the past several commits I have not been able to get the workflow to execute and I can not find anything that would exclude it from the list of workflows to run. Unfortunately there does not seem to be any diagnostics I can inspect to get an idea why the workflow is not getting triggered. 

@FreeTAKTeam/gitdevs  Any ideas or anyone really experienced with GitHub Actions?

**Comment by hickey** [comment]
No sooner do I add a comment about my problems with GitHub Actions and then poke around some more after the comment and find a page that tells me that the reference to `GITHUB_REF_NAME` is invalid. I make a couple of changes and things are now getting scheduled again. Disregard my request for help with the workflow....for now 😄

**Comment by brothercorvo** [comment]
@HeroesLament  is the best we have for this kind of stuff

**Comment by hickey** [comment]
Basic configuration of this Docker image _should_ work (but still untested at this point) with both YAML config and env vars. Once #386 is merged, this branch should be able to be rebased and adopt the new configuration infrastructure. 

Of course saying that I think the `Dockerfile` is still using the released FTS packages rather than the source from the branch. So that work needs to be focused on.

**Comment by hickey** [comment]
Manual builds of the Docker image is looking pretty decent. The test failures are due to #408 not being merged yet.

**Comment by hickey** [comment]
Since I was gone for quite a while with the move across the country I tried to rebase this PR against the current master. There are a **lot** of changes to the structure of the project. It was way too confusing trying to resolve all the conflicts, so I have started a new branch `docker2` (yes, real creative) off the current master to move changes on to. This should be significantly faster turning around than trying to determine what changes should be accepted to resolve conflicts.

**Comment by brothercorvo** [comment]
@hickey please let me know when you are available to discuss the changes

**Pull request closed without merging**
