### PR TITLE
426 instantiate wizard before main config is accessed

### PR DESCRIPTION
**Pull request by dlc-ariel**

### CODE REVIEW

**Comment by dlc-ariel** [comment]
I believe there is one more issue where the config is referenced using its default values in the Component registration where it pulls values in from DataPackageServer variables so making a draft in the meantime

**Comment by naman108** [comment]
> I believe there is one more issue where the config is referenced using its default values in the Component registration where it pulls values in from DataPackageServer variables so making a draft in the meantime

could you outline how to reproduce this error?

**Comment by brothercorvo** [comment]
@dlc-ariel can you do another commit, so that we re-run the checks?

**Comment by dlc-ariel** [comment]
This pr should be good to go. This pr does __not__ solve the issue where any references to config attributes that use MAINPATH resolve to the actual config value if not the default. There are a few ways to mitigate this issue but I feel it is better suited to be resolved in #408

**Comment by brothercorvo** [comment]
merging this, so that @dlc-ariel can take care of the issues in the Datapackage.py

**Pull request merged**
